# Generated by Django 4.0 on 2023-05-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(blank=True, max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Level',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Material Type',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('has_chapter_content', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
                ('pdf_URL', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subject_MaterialType', to='graduate.materialtype')),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='SemYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_year_num', models.PositiveSmallIntegerField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SemYear_Level', to='graduate.level')),
            ],
            options={
                'verbose_name_plural': 'Semester Year',
            },
        ),
        migrations.AddField(
            model_name='materialtype',
            name='sem_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialType_SemYear', to='graduate.semyear'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.PositiveSmallIntegerField(null=True)),
                ('content', models.CharField(blank=True, max_length=300)),
                ('pdf_URL', models.URLField(default='', max_length=220)),
                ('is_pdf', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_Subject', to='graduate.subject')),
            ],
            options={
                'verbose_name_plural': 'Chapter',
            },
        ),
    ]
