# Generated by Django 4.2.1 on 2023-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.PositiveSmallIntegerField(null=True)),
                ('content', models.CharField(max_length=300, null=True)),
                ('pdf_URL', models.URLField(default='', max_length=220)),
                ('Is_pdf', models.BooleanField(default=False)),
                ('Is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, null=True)),
                ('Is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('Is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SemYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_year_num', models.PositiveSmallIntegerField(null=True)),
                ('Is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, null=True)),
                ('has_chapter_content', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=300, null=True)),
                ('pdf_URL', models.URLField()),
                ('Is_pdf', models.BooleanField(default=False)),
                ('Is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_choices', models.CharField(choices=[('un1', 'university 1'), ('un2', 'university 2'), ('un3', 'university 3')], max_length=10)),
                ('faculty_choices', models.CharField(choices=[('fc1', 'faculty 1'), ('fc2', 'faculty 2'), ('fc3', 'faculty 3')], max_length=10)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('marks', models.PositiveSmallIntegerField(null=True)),
                ('Is_shown', models.BooleanField(default=False)),
            ],
        ),
    ]
