# Generated by Django 4.2.1 on 2023-06-07 06:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialcontent',
            name='has_chapter_content',
            field=models.BooleanField(default=False),
        ),
    ]
