# Generated by Django 4.2.1 on 2023-05-21 01:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
