# Generated by Django 4.2.1 on 2023-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeinfo',
            name='Is_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='faculty_choices',
            field=models.CharField(choices=[('fc1', 'faculty 1'), ('fc2', 'faculty 2'), ('fc3', 'faculty 3')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='no_of_student',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='university_choices',
            field=models.CharField(choices=[('un1', 'university 1'), ('un2', 'university 2'), ('un3', 'university 3')], default='', max_length=10),
        ),
    ]
