# Generated by Django 4.2.1 on 2023-06-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0002_subcontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontent',
            options={'verbose_name_plural': 'Sub Content'},
        ),
    ]
