# Generated by Django 4.2.1 on 2023-06-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0002_alter_materialcontent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcontent',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialcontent_level', to='graduate.level'),
        ),
    ]
