# Generated by Django 4.2.1 on 2023-06-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_alter_subcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontent',
            name='material_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontent_materialcontent', to='graduate.materialcontent'),
        ),
    ]
