# Generated by Django 4.2.1 on 2023-06-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_materialcontent_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcontent',
            name='level',
        ),
    ]
