# Generated by Django 4.2.1 on 2023-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_alter_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='materialtype',
            table='Material Type',
        ),
    ]
