# Generated by Django 4.2.1 on 2023-08-24 10:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0004_alter_subcontent_material_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
