# Generated by Django 4.2.1 on 2023-05-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0004_alter_materialtype_slug_alter_materialtype_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='is_visible',
            new_name='is_shown',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='is_visible',
            new_name='is_shown',
        ),
        migrations.RenameField(
            model_name='materialtype',
            old_name='is_visible',
            new_name='is_shown',
        ),
        migrations.RenameField(
            model_name='semyear',
            old_name='is_visible',
            new_name='is_shown',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='is_visible',
            new_name='is_shown',
        ),
    ]
