# Generated by Django 4.2.1 on 2023-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0005_rename_is_visible_chapter_is_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chapter',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='level',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='level',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='level',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='level',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='semyear',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='semyear',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='semyear',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='semyear',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
