# Generated by Django 4.2.1 on 2023-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0006_chapter_seo_description_chapter_seo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semyear',
            name='is_year',
            field=models.BooleanField(default=True),
        ),
    ]
