# Generated by Django 4.2.1 on 2023-06-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0010_chapter_slug_level_slug_semyear_slug_subject_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='sem_year',
        ),
        migrations.AddField(
            model_name='materialtype',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialType_Level', to='graduate.level'),
        ),
    ]
