# Generated by Django 4.2.1 on 2023-06-04 11:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0011_remove_materialtype_sem_year_materialtype_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='has_chapter_content',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_pdf',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pdf_URL',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='seo_image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='seo_keyword',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_level', to='graduate.level'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_semyear', to='graduate.semyear'),
        ),
        migrations.CreateModel(
            name='MaterialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_chapter_content', models.BooleanField(default=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('pdf_URL', models.URLField()),
                ('is_pdf', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=50)),
                ('seo_keyword', models.CharField(blank=True, max_length=200)),
                ('seo_image', models.ImageField(blank=True, null=True, upload_to='seo_images/')),
                ('seo_description', models.TextField(blank=True)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialcontent_materialtype', to='graduate.materialtype')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialcontent_subject', to='graduate.subject')),
            ],
            options={
                'verbose_name_plural': 'Material Content',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='material_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_materialcontent', to='graduate.materialcontent'),
        ),
    ]
