# Generated by Django 4.2.1 on 2023-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0012_remove_chapter_subject_remove_subject_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcontent',
            name='has_chapter_content',
            field=models.BooleanField(default=True),
        ),
    ]
