# Generated by Django 4.2.1 on 2023-08-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
