# Generated by Django 4.2.1 on 2023-08-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_verified_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_email_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
