# Generated by Django 4.0 on 2023-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_shown', models.BooleanField(default=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Entrance',
            new_name='PastQuestion',
        ),
        migrations.AddField(
            model_name='gk',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
