# Generated by Django 4.0 on 2023-05-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_modelquestion_rename_entrance_pastquestion_gk_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gk',
            options={'verbose_name': 'GK'},
        ),
    ]
