# Generated by Django 4.0 on 2023-05-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_alter_gk_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gk',
            options={'verbose_name_plural': 'GK'},
        ),
    ]
