# Generated by Django 4.0 on 2023-05-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_alter_gk_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastquestion',
            options={'verbose_name_plural': 'PastQuestion'},
        ),
    ]
