# Generated by Django 4.0 on 2023-05-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_alter_pastquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeinfo',
            options={'verbose_name_plural': 'College Info'},
        ),
        migrations.AlterModelOptions(
            name='modelquestion',
            options={'verbose_name_plural': 'Model Question'},
        ),
        migrations.AlterModelOptions(
            name='syllabusinfo',
            options={'verbose_name_plural': 'Syllabus Info'},
        ),
    ]
