# Generated by Django 4.2.1 on 2023-05-21 05:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_alter_collegeinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gk',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
