# Generated by Django 4.2.1 on 2023-05-21 06:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_alter_gk_content_alter_pastquestion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelquestion',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
