# Generated by Django 4.2.1 on 2023-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_alter_modelquestion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='gk',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gk',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='gk',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gk',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
