# Generated by Django 4.2.1 on 2023-05-22 12:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0013_collegeinfo_seo_description_collegeinfo_seo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gk',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
