# Generated by Django 4.2.1 on 2023-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0014_alter_gk_content_alter_modelquestion_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelquestion',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='types',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
