# Generated by Django 4.2.1 on 2023-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0015_modelquestion_year_pastquestion_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusinfo',
            name='no_of_question',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='university_choices',
            field=models.CharField(choices=[('un1', 'AFU'), ('un2', 'TU'), ('un3', 'PU')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabusinfo',
            name='university_choices',
            field=models.CharField(blank=True, choices=[('un1', 'AFU'), ('un2', 'TU'), ('un3', 'PU')], max_length=10),
        ),
    ]
