# Generated by Django 4.2.1 on 2023-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0016_syllabusinfo_no_of_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinfo',
            name='faculty_choices',
            field=models.CharField(choices=[('B.V.Sc and A.H', 'B.V.Sc and A.H / B.Sc Fisheries'), ('B.Sc Agriculture', 'B.Sc Agriculture'), ('B.Sc Forestry', 'B.Sc Forestry')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='university_choices',
            field=models.CharField(choices=[('AFU', 'Agriculture and Forestry University'), ('TU', 'Tribhuvan University'), ('PU', 'Purwanchal University')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusinfo',
            name='faculty_choices',
            field=models.CharField(blank=True, choices=[('B.V.Sc and A.H', 'B.V.Sc and A.H / B.Sc Fisheries'), ('B.Sc Agriculture', 'B.Sc Agriculture'), ('B.Sc Forestry', 'B.Sc Forestry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusinfo',
            name='university_choices',
            field=models.CharField(blank=True, choices=[('AFU', 'Agriculture and Forestry University'), ('TU', 'Tribhuvan University'), ('PU', 'Purwanchal University')], max_length=100),
        ),
    ]
