# Generated by Django 4.2.1 on 2023-05-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0017_alter_collegeinfo_faculty_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeinfo',
            old_name='department',
            new_name='quota_name',
        ),
    ]
