# Generated by Django 4.2.1 on 2023-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0018_rename_department_collegeinfo_quota_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelquestion',
            name='year',
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='model_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
