# Generated by Django 4.0 on 2023-05-19 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=50)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('short_description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
