# Generated by Django 4.2.1 on 2023-05-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_keyword',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
    ]
