# Generated by Django 4.0 on 2023-05-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0003_alter_post_short_description_postviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postviews',
            options={'verbose_name_plural': 'Post Views'},
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes_post', to='blog.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikes_user', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Post Likes',
            },
        ),
    ]
