# Generated by Django 4.2.1 on 2023-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
