# Generated by Django 4.0 on 2023-05-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0004_alter_postviews_options_postlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userViews_post', to='blog.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userViews_user', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'User Views',
            },
        ),
    ]
