# Generated by Django 4.0 on 2023-05-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postDescription_post', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Post Description',
            },
        ),
    ]
