# Generated by Django 4.0 on 2023-05-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posttags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postcomments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postcomments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postdescription',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posttags',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postviews',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userviews',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
