# Generated by Django 4.2.1 on 2023-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userviews',
            name='count',
            field=models.SmallIntegerField(null=True),
        ),
    ]
