# Generated by Django 4.2.1 on 2023-05-21 06:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_id_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdescription',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
