# Generated by Django 4.2.1 on 2023-05-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postdescription_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'PostCategory',
            },
        ),
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=30)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featurePost_post', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Feature Post',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_postCategory', to='blog.postcategory'),
        ),
    ]
