# Generated by Django 4.2.1 on 2023-05-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postcategory_featurepost_post_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post Category'},
        ),
    ]
