# Generated by Django 4.2.1 on 2023-05-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_postcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
