# Generated by Django 4.2.1 on 2023-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.SmallIntegerField(null=True),
        ),
    ]
