# Generated by Django 4.2.1 on 2023-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_share_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'featured-post-top'), ('2', 'featured-post-bottom-1st'), ('3', 'featured-post-bottom-2nd-top'), ('4', 'featured-post-bottom-2nd-lower'), ('5', 'featured-post-bottom-3rd-top'), ('6', 'featured-post-bottom-3rd-bottom-item-1'), ('7', 'featured-post-bottom-3rd-bottom-item-2'), ('8', 'featured-post-bottom-3rd-bottom-item-3')], max_length=100),
        ),
    ]
