# Generated by Django 4.0 on 2023-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_choices', models.CharField(choices=[('un1', 'university 1'), ('un2', 'university 2'), ('un3', 'university 3')], default='', max_length=10)),
                ('faculty_choices', models.CharField(choices=[('fc1', 'faculty 1'), ('fc2', 'faculty 2'), ('fc3', 'faculty 3')], default='', max_length=10)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('no_of_student', models.PositiveSmallIntegerField(null=True)),
                ('is_shown', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pdf_url', models.URLField()),
                ('is_shown', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilModelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown', models.BooleanField(default=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilPastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pdf_url', models.URLField()),
                ('is_shown', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoksewaModelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown', models.BooleanField(default=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LoksewaNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown', models.BooleanField(default=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LoksewaPastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('pdf_url', models.URLField()),
                ('is_pdf', models.BooleanField(default=False)),
                ('content', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_choices', models.CharField(blank=True, choices=[('un1', 'university 1'), ('un2', 'university 2'), ('un3', 'university 3')], max_length=10)),
                ('faculty_choices', models.CharField(blank=True, choices=[('fc1', 'faculty 1'), ('fc2', 'faculty 2'), ('fc3', 'faculty 3')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('marks', models.PositiveSmallIntegerField(null=True)),
                ('is_shown', models.BooleanField(default=True)),
            ],
        ),
    ]
