# Generated by Django 4.0 on 2023-05-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeinfo',
            options={'verbose_name_plural': 'College Info'},
        ),
        migrations.AlterModelOptions(
            name='councilact',
            options={'verbose_name_plural': 'Council Act'},
        ),
        migrations.AlterModelOptions(
            name='councilmodelquestion',
            options={'verbose_name_plural': 'Council Model Question'},
        ),
        migrations.AlterModelOptions(
            name='councilpastquestion',
            options={'verbose_name_plural': 'Council Past Question'},
        ),
        migrations.AlterModelOptions(
            name='councilregulation',
            options={'verbose_name_plural': 'Council Regulation'},
        ),
        migrations.AlterModelOptions(
            name='loksewamodelquestion',
            options={'verbose_name_plural': 'Loksewa Model Question'},
        ),
        migrations.AlterModelOptions(
            name='loksewanotes',
            options={'verbose_name_plural': 'Loksewa Notes'},
        ),
        migrations.AlterModelOptions(
            name='loksewapastquestion',
            options={'verbose_name_plural': 'Loksewa Past Question'},
        ),
        migrations.AlterModelOptions(
            name='syllabusinfo',
            options={'verbose_name_plural': 'Syllabus Info'},
        ),
    ]
