# Generated by Django 4.0 on 2023-05-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0002_alter_collegeinfo_options_alter_councilact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loksewanotes',
            options={'verbose_name_plural': 'Loksewa Note'},
        ),
    ]
