# Generated by Django 4.2.1 on 2023-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0005_collegeinfo_seo_description_collegeinfo_seo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmodelquestion',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='councilpastquestion',
            name='types',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='loksewamodelquestion',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loksewanotes',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loksewapastquestion',
            name='types',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
