# Generated by Django 4.2.1 on 2023-05-23 13:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0006_councilmodelquestion_name_councilpastquestion_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmodelquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='councilpastquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='loksewamodelquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='loksewanotes',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='loksewapastquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
