# Generated by Django 4.2.1 on 2023-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0007_alter_councilmodelquestion_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmodelquestion',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='councilpastquestion',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loksewamodelquestion',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loksewanotes',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loksewapastquestion',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
