# Generated by Django 4.2.1 on 2023-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_graduate', '0008_alter_councilmodelquestion_is_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeinfo',
            old_name='department',
            new_name='quota_name',
        ),
        migrations.AddField(
            model_name='syllabusinfo',
            name='no_of_question',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
