# Generated by Django 4.2.1 on 2023-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_ads_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experts',
            name='description',
        ),
        migrations.AddField(
            model_name='experts',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experts',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='experts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expert_images/'),
        ),
        migrations.AddField(
            model_name='experts',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='experts',
            name='organization',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experts',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
