# Generated by Django 4.2.1 on 2023-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_experts_description_experts_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_notice_images/')),
                ('url', models.URLField()),
                ('is_shown', models.BooleanField(default=True)),
                ('is_news', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Notice',
            },
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
