# Generated by Django 4.2.1 on 2023-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_newsandnotice_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribe', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News Letter',
            },
        ),
        migrations.AlterModelOptions(
            name='newsandnotice',
            options={'verbose_name_plural': 'News and Notice'},
        ),
    ]
