# Generated by Django 4.2.1 on 2023-05-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(max_length=254)),
                ('is_shown', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Useful Links',
            },
        ),
    ]
