# Generated by Django 4.2.1 on 2023-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_usefullinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(blank=True, max_length=50)),
                ('composition', models.CharField(blank=True, max_length=100)),
                ('indication_contraindication', models.CharField(blank=True, max_length=300)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='drug_index_images/')),
                ('is_shown', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Drug Index',
            },
        ),
    ]
