# Generated by Django 4.2.1 on 2023-05-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_drugindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experts',
            options={'verbose_name_plural': 'Experts'},
        ),
    ]
