# Generated by Django 4.2.1 on 2023-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_experts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugindex',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drugindex',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='drugindex',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drugindex',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='krishidiarys',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='krishidiarys',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='krishidiarys',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='krishidiarys',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='newsandnotice',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsandnotice',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='newsandnotice',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsandnotice',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
