# Generated by Django 4.2.1 on 2023-05-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_drugindex_seo_description_drugindex_seo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
    ]
