# Generated by Django 4.2.1 on 2023-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_experts_is_shown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krishidiarys',
            options={'verbose_name_plural': 'Krishi Diarys'},
        ),
        migrations.AlterField(
            model_name='usefullinks',
            name='url',
            field=models.URLField(),
        ),
    ]
