# Generated by Django 4.2.1 on 2023-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_alter_krishidiarys_options_alter_usefullinks_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandnotice',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsandnotice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
