# Generated by Django 4.2.1 on 2023-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_newsandnotice_author_newsandnotice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
