# Generated by Django 4.2.1 on 2023-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_alter_newsandnotice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='position',
            field=models.CharField(blank=True, choices=[('0', 'Zero'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Five'), ('6', 'Six')], max_length=30),
        ),
    ]
